### ISSUE TITLE
Documentation to-do list

### ISSUE THREAD

**Issue by sallain** [artefactual-sdps/enduro#751]
- [x] Move intro text to homepage - #752
- [ ] Add instructions on configuring preservation options
- [ ] Add Troubleshooting info
